config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  root "posts#index"
  resources :posts do
    resources :comments, only: :create
    resources :likes, only: [:create, :destroy]
    collection do
      get :search
    end
  end

  resources :users, only: :show do
    member do
      get :mylist
      get :mycomment
      get :myliked
    end
  end

  resources :categories, only: :show

end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :post_category_relations
  has_many :posts, through: :post_category_relations
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :comment, length: { maximum: 200 }, presence: true
end

app/models/like.rb
# frozen_string_literal: true

class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :user
  has_one :restaurant, dependent: :destroy
  accepts_nested_attributes_for :restaurant
  has_many :post_category_relations, dependent: :destroy
  has_many :categories, through: :post_category_relations
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post

  mount_uploader :img, ImgUploader

  validates :title, length: { maximum: 40 }, presence: true
  validates :body, length: { maximum: 1000 }, presence: true
  validate :category_check
  validate :img_check
  def already_liked?(user)
    likes.find_by(user_id: user.id)
  end

  private

  def img_check
    if img.present?
      errors.add(:img, 'の拡張子がJPEGまたはPNGを挿入してください') unless img.content_type.in?(%('image/jpeg image/png'))
    else
      errors.add(:img, 'を挿入してください')
    end
  end

  def category_check
    errors.add(:category_ids, 'のおすすめを選択してください') unless category_ids.present?
  end
end

app/models/post_category_relation.rb
# frozen_string_literal: true

class PostCategoryRelation < ApplicationRecord
  belongs_to :post
  belongs_to :category
end

app/models/restaurant.rb
# frozen_string_literal: true

class Restaurant < ApplicationRecord
  belongs_to :post

  validate :restaurant_check

  private

  def restaurant_check
    errors.add(:name, 'を登録してください') unless name.present?
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[google_oauth2 twitter]

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes
  has_many :liked_users, through: :likes, source: :user

  validates :nickname, presence: true, length: { maximum: 50 }
  def self.from_omniauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first
    if user.nil?
      user = User.create(
        uid: auth.uid,
        provider: auth.provider,
        nickname: auth.info.name,
        email: User.dummy_email(auth),
        password: Devise.friendly_token[0, 20]
      )
    end
    user
  end

  def self.dummy_email(auth)
    "#{auth.uid}-#{auth.provider}@example.com"
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit :sign_up, keys: [:nickname]
  end
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
    @categories = Category.all
    @posts = @category.posts.order(created_at: :desc).page(params[:page]).per(8)
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @comment.save
    respond_to do |format|
      format.html { redirect_to post_path(params[:post_id]) }
      format.json
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:comment).merge(user_id: current_user.id, post_id: params[:post_id])
  end
end

app/controllers/likes_controller.rb
# frozen_string_literal: true

class LikesController < ApplicationController
  def create
    @like = current_user.likes.create(post_id: params[:post_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
    @like.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show search]
  before_action :set_post, only: %i[show edit update destroy]
  before_action :set_categories, only: %i[index show search]

  def index
    @posts = Post.includes(:user).order(created_at: :desc).page(params[:page]).per(8)
  end

  def new
    @post = Post.new
  end

  def show
    @comments = @post.comments.includes(:user)
    @comment = Comment.new
    @like = Like.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to root_path, notice: '記事を投稿しました'
    else
      render :new
    end
  end

  def edit
    if user_signed_in? && current_user.id == @post.user.id
      render :edit
    else
      redirect_to root_path, alert: '記事を編集出来ません。'
    end
  end

  def update
    if @post.update(post_params)
      redirect_to mylist_user_path(@post.user), notice: '記事を編集しました。'
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to mylist_user_path(@post.user), notice: '記事を削除しました。'
  end

  def search
    @posts = query.order(created_at: :desc).page(params[:page]).per(8)
  end

  private

  def post_params
    params.require(:post)
          .permit(:title, :body, :img, category_ids: [], restaurant_attributes: %i[id name url])
          .merge(user_id: current_user.id)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def set_categories
    @categories = Category.all
  end

  def query
    params[:post].present? && params[:post][:keyword]
    Post.joins(:restaurant).where('title LIKE ? OR body LIKE ? OR name LIKE ?',
                                  "%#{params[:post][:keyword]}%",
                                  "%#{params[:post][:keyword]}%",
                                  "%#{params[:post][:keyword]}%")
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    callback_for(:google)
  end

  def twitter
    callback_for(:twitter)
  end

  def callback_for(provider)
    @user = User.from_omniauth(request.env['omniauth.auth'])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: provider.to_s.capitalize) if is_navigational_format?
    else
      session["devise.#{provider}_data"] = request.env['omniauth.auth'].except('extra')
      redirect_to new_user_registration_path
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_params
  def mylist
    @posts = @user.posts.order(created_at: :desc).page(params[:page]).per(8)
  end

  def mycomment
    @comment_posts = @user.comments.order(created_at: :desc)
    @array_posts = @comment_posts.map(&:post).flatten
    @posts = Kaminari.paginate_array(@array_posts).page(params[:page]).per(8)
  end

  def myliked
    @liked_posts = @user.likes.order(created_at: :desc)
    @array_posts = @liked_posts.map(&:post).flatten
    @posts = Kaminari.paginate_array(@array_posts).page(params[:page]).per(8)
  end

  private

  def set_params
    @user = User.find(params[:id])
    @categories = Category.all
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/categories/_upperbar.html.erb
<div class="upperbar">
  <div class="upperbar-title">
    <h1 class="title is-1"><%= @category.name %>串の投稿一覧</h1>
  </div>
</div>

app/views/categories/show.html.erb
<%= render 'shared/header' %>

<%= render 'shared/sidebar' %>

<%= render 'categories/upperbar' %>

<div class="mylist">
  <div id="modal-section"></div>
  <%= render partial: 'shared/post', collection: @posts %>
</div>

<%= paginate @posts %>

<%= render 'shared/footer' %>

app/views/layouts/_notifications.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "#{key}") %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YakitoriApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.5/css/bulma.css" />
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_upperbar.html.erb
<div class="upperbar">
  <div class="upperbar-title">
    <h1 class="title is-1">"<%= params[:post][:keyword] %>"の検索結果</h1>
  </div>
</div>

app/views/posts/edit.html.erb
<%= render 'shared/logo' %>

<div class="editpost">
  <div class="editpost-card">
    <h2 class="editpost-title">編集する</h2>
    <%= form_for @post do |f| %>
      <div class="field" id="img-field"> 
        <%= f.label :img, class: "label" %>
        <%= image_tag @post.img.url, id: "img_prev", onClick: "$('#post_img').click()" %>
        <%= f.file_field :img, id: "post_img", style:"display:none;" %>
        <p class="error">
          <%= @post.errors.full_messages_for(:img)[0] if @post.errors.any? %>
        </p>
      </div>

      <div class="field" id="title-field"> 
        <%= f.label :title, class: "label" %>
        <%= f.text_field :title %>
        <p class="error">
          <%= @post.errors.full_messages_for(:title)[0] if @post.errors.any? %>
        </p>
      </div>

      <div class="field" id="body-field">
        <%= f.label :body, class: "label" %>
        <%= f.text_area :body %>
        <p class="error">
          <%= @post.errors.full_messages_for(:body)[0] if @post.errors.any? %>
        </p>
      </div>

      <div class="field" id="category-field">
        <%= f.label "おすすめの焼き鳥", class: "label" %>
        <div class="category-index">
          <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) do |category| %>
            <%= category.label class: "category-parts" do %>
              <%= category.check_box %>
              <p class="parts"><%= category.text %></p>
            <% end %>
          <% end %>
        </div>
        <p class="error">
          <%= @post.errors.full_messages_for(:category_ids)[0] if @post.errors.any? %>
        </p>
      </div>


      <%= f.fields_for :restaurant, @post.restaurant || Restaurant.new do |p|%>  
        <div class="field" id="restaurant-field">
          <%= f.label "店舗", class: "label" %>
          <input class="input" type="text" id="key" placeholder="キーワードを入力してください">
          <input class="button is-warning" type="button" id="search" value="検索">
          <p class="error">
            <%= @post.errors.full_messages_for(:"restaurant.name")[0] if @post.errors.any? %>
          </p>
          <ul id="ul"></ul>
            <%= p.hidden_field :name, id: "rest_name" %>
            <%= p.hidden_field :url , id: "rest_url" %>
        </div>
      <% end %>


      <div class="actions">
        <%= f.submit "変更する", class: "edit-button" %>
      </div>
      
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<%= render 'shared/header' %>

<%= render 'shared/sidebar' %>

<%= render 'shared/upperbar' %>

<%= render 'layouts/notifications' %>

<div class="contents">
  <%= render partial: 'shared/post', collection: @posts %>
</div>

<div id="modal-section"></div>

<%= paginate @posts %>

<%= render 'shared/footer' %>

app/views/posts/new.html.erb
<%= render 'shared/logo' %>

<div class="newpost">
  <div class="newpost-card">
    <h2 class="newpost-title">投稿する</h2>
    <%= form_for @post do |f| %>
      <div class="field" id="img-field"> 
        <%= f.label :img, class: "label" %>
        <%= image_tag asset_path("no_image.png"), id: "img_prev", onClick: "$('#post_img').click()" %>
        <%= f.file_field :img, id: "post_img", style:"display:none;" %>
        <p class="error">
          <%= @post.errors.full_messages_for(:img)[0] if @post.errors.any? %>
        </p>
      </div>

      <div class="field" id="title-field"> 
        <%= f.label :title, class: "label" %>
        <%= f.text_field :title %>
        <p class="error">
          <%= @post.errors.full_messages_for(:title)[0] if @post.errors.any? %>
        </p>
      </div>

      <div class="field" id="body-field">
        <%= f.label :body, class: "label" %>
        <%= f.text_area :body %>
        <p class="error">
          <%= @post.errors.full_messages_for(:body)[0] if @post.errors.any? %>
        </p>
      </div>

      <div class="field" id="category-field">
        <%= f.label "おすすめの焼き鳥", class: "label" %>
        <div class="category-index">
          <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) do |category| %>
            <%= category.label class: "category-parts" do %>
              <%= category.check_box %>
              <p class="parts"><%= category.text %></p>
            <% end %>
          <% end %>
        </div>
        <p class="error">
          <%= @post.errors.full_messages_for(:category_ids)[0] if @post.errors.any? %>
        </p>
      </div>

      <%= f.fields_for :restaurant, @post.restaurant || Restaurant.new do |p|%>  
        <div class="field" id="restaurant-field">
          <%= f.label "店舗", class: "label" %>
          <input class="input" type="text" id="key" placeholder="キーワードを入力してください">
          <input class="button is-warning" type="button" id="search" value="検索">
          <p class="error">
            <%= @post.errors.full_messages_for(:"restaurant.name")[0] if @post.errors.any? %>
          </p>
          <ul id="ul"></ul>
            <%= p.hidden_field :name, id: "rest_name" %>
            <%= p.hidden_field :url , id: "rest_url" %>
        </div>
      <% end %>

      <div class="actions">
        <%= f.submit "投稿する", class: "post-button" %>
      </div>

    <% end %>
  </div>
</div>

app/views/posts/search.html.erb
<%= render 'shared/header' %>

<%= render 'posts/upperbar' %>

<div class="contents">
  <%= render partial: 'shared/post', collection: @posts %>
</div>

<%= paginate @posts %>

<%= render 'shared/footer' %>

app/views/posts/show.html.erb
<%= render 'shared/header' %>

<div class="show">
  <div class="show-background">
    <div class="show-card">
      <header class="card-header" id="show-header">
        <div class="show-left">
          <h5 class="subtitle is-5">
            <%= link_to "#{@post.user.nickname}", mylist_user_path(@post.user),id: "show-user" %>
          </h5>
          <% if user_signed_in?%>
            <% if @post.already_liked?(current_user) %>
              <%= link_to post_like_path(@post), method: :delete, id: "like" do %>
                <span class="icon" id="like-icon">
                  <i class="fa fa-heart"></i>
                  <p class= "like"><%= @post.likes.count %></p>
                </span>
              <% end %>
            <% else %>
              <%= link_to post_likes_path(@post), method: :post, id: "nolike" do %>
                <span class="icon" id="nolike-icon">
                  <i class="fa fa-heart"></i>
                  <p class= "like"><%= @post.likes.count %></p>
                </span>
              <% end %>
            <% end %>
          <% else %>
            <span class="icon" id="nolike-icon">
              <i class="fa fa-heart"></i>
              <p class= "like"><%= @post.likes.count %></p>
            </span>
          <% end %>

          <% if user_signed_in? && current_user.id == @post.user.id %>
            <%= link_to edit_post_path(@post.id), method: :get, id: "edit-icon" do %>
              <span class="icon" id="show-icon">
                <i class="far fa-edit"></i>
              </span>
            <% end %>
            <%= link_to post_path(@post.id), method: :delete, id: "del-icon", data: {confirm: "削除しますか？"} do %>
              <span class="icon" id="show-icon">
                <i class="fas fa-trash"></i>
              </span>
            <% end %>
          <% end %>
        </div>
      </header>
      <section class="show-card-body">
        <h3 class="subtitle is-3" id="show-title">
          <%= @post.title %>
        </h3>
    
        <% if @post.img.present? %>
          <%= image_tag @post.img.url, id: "show-line" %>
        <% else %>
          <%= image_tag "https://bulma.io/images/placeholders/1280x960.png",  id: "modal-body" %>
        <% end %>
        <div class='field' id="show-body">
          <p><%= simple_format(@post.body) %></p>
        </div>

        <div class='field' id="show-line">
          <h6 class="title is-6">【オススメの焼き鳥】</h6>
          <% @post.categories.each do |category| %>
            <p><%= category.name %></p>
          <% end %>
        </div>

        <div class='field' id="show-line">
          <h6 class="title is-6">【店舗情報】</h6>
          <p><%= @post.restaurant.name %></p> 
          <%= button_to "店舗詳細", "#{@post.restaurant.url}", class: "button"%>
        </div>

        <div class="show-comment">
          <% if user_signed_in? %>
            <%= form_for [@post, @comment] do |f| %>
              <div class="field">
                <div class="control">
                  <%= f.text_area :comment, class: "textarea", id: "comment-area", placeholder: "コメントを入力してください" %>
                  <div class="comment-error"></div>
                  <%= f.submit "コメントする", class: "button is-warning", id: "comment-button" %>
                </div>
              </div>
            <% end %>
          <% end %>
          <div class="comment-index">
            <h6 class="title is-6">【コメント一覧】</h6>
              <% if @comments %>
                <% @comments.each do |comment| %>
                  <p>
                    <strong><%= link_to comment.user.nickname, mylist_user_path(comment.user) %>：</strong>
                    <%= comment.comment %>
                  </p>
                <% end %>
              <% end %>
          </div>
        </div>
      </section>
    </div>
  </div>
</div>

<%= render 'shared/footer' %>

app/views/shared/_footer.html.erb
<div id="footer">
  <p class="subtitle is-6">~とりコミュ~</p>
</div>

app/views/shared/_header.html.erb
<nav class="navbar is-black">
  <div class="navbar-brand">
    <%= link_to root_path, class:"navbar-item" do %>
      <h4 class="title is-4" id="header-logo">~とりコミュ~</h4>
    <% end %>
    <div class="navbar-burger burger" data-target="navbarExampleTransparentExample">
      <span></span>
      <span></span>
      <span></span>
    </div>
  </div>

  <div id="navbarExampleTransparentExample" class="navbar-menu">
    <div class="navbar-start">
      <% if user_signed_in? %>
        <div class="navbar-item">
          <%= link_to "投稿する", new_post_path, class: "button is-warning", id: "header-button"%>
        </div>
      <% else %>
        <div class="navbar-item">
          <div class="field is-grouped">
            <%= link_to "メールで新規登録", new_user_registration_path, class: "button is-warning", id: "header-button" %>
            <span id="header-span">または</span>
            <%= link_to user_twitter_omniauth_authorize_path, method: :post, class: "button is-info", id: "twitter-signup" do %>
              <i class="fab fa-twitter"></i>
            <% end %>
            <%= link_to user_google_oauth2_omniauth_authorize_path, method: :post, class: "button", id: "google-signup" do %>
              <i class="fab fa-google"></i>
            <% end %>
          </div>
        </div>
      <% end %>

      <div class="navbar-item has-dropdown is-hoverable" id="dropdown">
        <a class="navbar-link title is-5">
          種類一覧
        </a>

        <div class="navbar-dropdown">
          <% @categories.each do |category| %>
            <%= link_to "#{category.name}", category_path(category), class: "navbar-item" %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <%= form_with model: Post.new, url: search_posts_path, method: :get, local: :true do |f|  %>
          <div class="field has-addons">
            <div class="control">
              <%= f.text_field :keyword, class: "input is-small", placeholder: "キーワードを入力" %>
            </div>
            <div class="control">
              <%= button_tag type: 'submit', class: "button is-small is-warning", id: "search-button" do %>
                <i class="fas fa-search"></i>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
      <div class="navbar-item">
        <div class="field is-grouped">
        <% if user_signed_in? %>
          <p class="control">
            <%= link_to "ログアウト", destroy_user_session_path, class: "title is-6", id: "header-link", method: :delete %>
          </p>
          <p class="control">
            <%= link_to "マイページ", mylist_user_path(current_user.id), class: "title is-6", id: "header-link" %>
          </p>
        <% else %>
          <%= link_to "ログイン", new_user_session_path, class: "title is-6", id: "header-link" %>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/shared/_logo.html.erb
<div id="logo">
  <%= link_to "~とりコミュ~", root_path, class: "title is-4", id: "logo-title" %>
</div>

app/views/shared/_post.html.erb
<%= link_to post_path(post), class: "post-item" do %>
  <div class="post-card">
    <div class="post-image">
      <%= image_tag post.img.url %>
      <div class="post-content">
        <h2 class="post-title">
          <%= post.title.truncate(10) %>
        </h2>
        <div class="post-lower">
          <div class="post-user">
            <%= post.user.nickname %>
          </div>
          <span class="icon" id="post-icon">
            <i class="fa fa-heart"></i>
            <p class= "like"><%= post.likes.count %></p>
          </span>
          <span class="icon" id="post-icon">
            <i class="fas fa-comment-alt"></i>
            <p class= "like"><%= post.comments.count %></p>
          </span>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_sidebar.html.erb
<div class="column" id="sidebar">
  <aside class="menu" id="menu">
    <p class="menu-label title is-5">
      種類一覧
    </p>
    <ul class="menu-list" id="sidebar-list">
      <% @categories.each do |category| %>
        <li>
          <%= link_to "#{category.name}", category_path(category), class: "sidebar-parts"%>
        </li>
      <% end %>
    </ul>
  </aside>
  <p class="hover">種類一覧</p>
</div>

app/views/shared/_upperbar.html.erb
<div class="upperbar">
  <div class="upperbar-title">
    <h1 class="title is-1">投稿一覧</h1>
    <h4 class="subtitle is-4">君の出会った焼き鳥を自慢しよう！</h4>
  </div>
</div>

app/views/users/_upperbar.html.erb
<div class="upperbar">
  <div class="upperbar-title">
    <h1 class="title is-1"><%= @user.nickname %>さんの投稿一覧</h1>
  </div>
</div>

app/views/users/mycomment.html.erb
<%= render 'shared/header' %>

<%= render 'shared/sidebar' %>

<%= render 'users/upperbar' %>

<div class="tabs is-centered" id="tabs">
  <ul>
    <li><%= link_to "マイリスト", mylist_user_path(@user) %></li>
    <li class="is-active"><%= link_to "コメント", mycomment_user_path(@user) %></li>
    <li><%= link_to "いいね", myliked_user_path(@user) %></li>
  </ul>
</div>

<div class="mylist">
  <div id="modal-section"></div>
  <%= render partial: 'shared/post', collection: @posts %>
</div>

<%= paginate @posts %>

<%= render 'shared/footer' %>

app/views/users/myliked.html.erb
<%= render 'shared/header' %>

<%= render 'shared/sidebar' %>

<%= render 'users/upperbar' %>

<div class="tabs is-centered" id="tabs">
  <ul>
    <li><%= link_to "マイリスト", mylist_user_path(@user) %></li>
    <li><%= link_to "コメント", mycomment_user_path(@user) %></li>
    <li class="is-active"><%= link_to "いいね", myliked_user_path(@user) %></li>
  </ul>
</div>

<div class="mylist">
  <div id="modal-section"></div>
  <%= render partial: 'shared/post', collection: @posts %>
</div>

<%= paginate @posts %>

<%= render 'shared/footer' %>

app/views/users/mylist.html.erb
<%= render 'shared/header' %>

<%= render 'shared/sidebar' %>

<%= render 'users/upperbar' %>

<div class="tabs is-centered" id="tabs">
  <ul>
    <li class="is-active"><%= link_to "マイリスト", mylist_user_path(@user) %></li>
    <li><%= link_to "コメント", mycomment_user_path(@user) %></li>
    <li><%= link_to "いいね", myliked_user_path(@user) %></li>
  </ul>
</div>

<%= render 'layouts/notifications' %>

<div class="mylist">
  <div id="modal-section"></div>
  <%= render partial: 'shared/post', collection: @posts %>
</div>

<%= paginate @posts %>

<%= render 'shared/footer' %>